name: Build Windows x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-prerelease: true
        msbuild-architecture: x64

    - name: Install Python
      run: |
        choco install python312 --params "/InstallDir:C:\Python312"

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Install Ninja
      run: |
          choco install ninja

    - name: Configure CMake
      env:
        TWITCH_CLIENT_SECRET: ${{ secrets.TwitchClientSecret }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      env:
        TWITCH_CLIENT_SECRET: ${{ secrets.TwitchClientSecret }}
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChatNotifier
        path: ${{github.workspace}}/build/bin/
